# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import smart_notebook_pb2 as smart__notebook__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in smart_notebook_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SmartNoteServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmbedDocument = channel.unary_unary(
                '/maumai.llm_agent.smart_notebook.v1.SmartNoteService/EmbedDocument',
                request_serializer=smart__notebook__pb2.EmbedRequest.SerializeToString,
                response_deserializer=smart__notebook__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.SummarizeDocument = channel.unary_unary(
                '/maumai.llm_agent.smart_notebook.v1.SmartNoteService/SummarizeDocument',
                request_serializer=smart__notebook__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=smart__notebook__pb2.SummarizeResponse.FromString,
                _registered_method=True)
        self.RagChat = channel.unary_stream(
                '/maumai.llm_agent.smart_notebook.v1.SmartNoteService/RagChat',
                request_serializer=smart__notebook__pb2.RagRequest.SerializeToString,
                response_deserializer=smart__notebook__pb2.RagResponse.FromString,
                _registered_method=True)


class SmartNoteServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EmbedDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RagChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmartNoteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmbedDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedDocument,
                    request_deserializer=smart__notebook__pb2.EmbedRequest.FromString,
                    response_serializer=smart__notebook__pb2.EmbedResponse.SerializeToString,
            ),
            'SummarizeDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeDocument,
                    request_deserializer=smart__notebook__pb2.SummarizeRequest.FromString,
                    response_serializer=smart__notebook__pb2.SummarizeResponse.SerializeToString,
            ),
            'RagChat': grpc.unary_stream_rpc_method_handler(
                    servicer.RagChat,
                    request_deserializer=smart__notebook__pb2.RagRequest.FromString,
                    response_serializer=smart__notebook__pb2.RagResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maumai.llm_agent.smart_notebook.v1.SmartNoteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('maumai.llm_agent.smart_notebook.v1.SmartNoteService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SmartNoteService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EmbedDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maumai.llm_agent.smart_notebook.v1.SmartNoteService/EmbedDocument',
            smart__notebook__pb2.EmbedRequest.SerializeToString,
            smart__notebook__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummarizeDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maumai.llm_agent.smart_notebook.v1.SmartNoteService/SummarizeDocument',
            smart__notebook__pb2.SummarizeRequest.SerializeToString,
            smart__notebook__pb2.SummarizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RagChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/maumai.llm_agent.smart_notebook.v1.SmartNoteService/RagChat',
            smart__notebook__pb2.RagRequest.SerializeToString,
            smart__notebook__pb2.RagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
